### ISSUE TITLE
 black screen

### ISSUE THREAD

**Issue by misterjbam** [vossstef/tang_nano_20k_c64#4]
Since the HDMI fixes made yesterday, I can no longer display an image.
I tested on different monitor.

**Comment by vossstef** [comment]
looks like by adjusting the main PLL for improved HDMI compatibility a stability issue popped up. 
will fix that in the neare future and revered temporary back to 40k bram as back-up.

**Comment by misterjbam** [comment]
thanks, it works again

**Comment by vossstef** [comment]
Hi misterjbam,
would you please be so kind and check on your setup this dram development branch ?
Mainly i simply adjusted DRAM timing....

older branch was working on one of my TN20k but on my 2nd spare part it also showed same black screen phaenomen.

**Comment by misterjbam** [comment]
I just tested dev_sdram and it's ok, I have the HDMI working

**Comment by vossstef** [comment]
thanks and will merge now
