### ISSUE TITLE
Primer 25k SDcard write core stall

### ISSUE THREAD

**Issue by vossstef** [vossstef/tang_nano_20k_c64#45]
hw control signal for sdcard might be missing

**Comment by harbaum** [comment]
Write protect on a micro SD card? How does that work?

**Comment by vossstef** [comment]
sorry my mistake. Just observed that core stalls when i press "save configuration".
Just figured out that a .ini had been written. 
Need to debug further

**Comment by vossstef** [comment]
no bug.
