### ISSUE TITLE
MultiLoad games from the C64 OneLoad collection (.CRT files) fail to run.

### ISSUE THREAD

**Issue by vanfanel** [vossstef/tang_nano_20k_c64#57]
That's about it: the MultiLoad games in the C64 OneLoad collection (they are .CRT files) fail to run, they all present a black screen.
Using original CBM kernal and 1541 ROM.

The C64 OneLoad collection v5 is the most famous C64 games collection and can be downloaded here:

https://mega.nz/file/WZUV2ApA#JFoFB3vVCcfiKe02TkTqq3JOR2OoWLWBGA2B8m_bxbI

**Comment by vossstef** [comment]
let me check on that that next week. So far i tried single files only.

**Comment by vossstef** [comment]
Bug confirmed.
solution available. To be included in next release

**Comment by vanfanel** [comment]
Great! I'm very glad to read that! In fact, it will make massive game testing way faster! :)

**Comment by vossstef** [comment]
@vanfanel 
is also this topic solved in the branch i created for testing?

**Comment by vanfanel** [comment]
@vossstef Yes, it's solved on that branch! 
In fact, I used that to test many of the games in CRT format! :+1: 

So I believe this can be closed, right?
