### ISSUE TITLE
Image not centered in PAL mode

### ISSUE THREAD

**Issue by vanfanel** [vossstef/tang_nano_20k_c64#60]
Hi there again, @vossstef 

This is a relatively small problem, but it's there and it would be nice to have image properly displayed.

On all my HDMI monitors, the core image is not centered: it's too low, as seen in this picture:

![c64_image_low](https://github.com/vossstef/tang_nano_20k_c64/assets/837585/6cf4cc7d-596d-4d00-bce4-a6068a44fe44)

So, maybe it has something to do with timings? Could it be centered?

Thanks!

**Comment by vossstef** [comment]
i fixed that an hour aho. pls check

**Comment by vanfanel** [comment]
@vossstef Tested! Image is perfectly centered in PAL mode now!!

![purrfect PAL image](https://github.com/vossstef/tang_nano_20k_c64/assets/837585/24f8cfe7-1906-4f03-86d3-64023091d7b0)

However, I noticed NTSC image is not centered (this time horizontally):

![impurrfect NTSC image](https://github.com/vossstef/tang_nano_20k_c64/assets/837585/5800af62-6430-4715-a580-defcaf8b1b0c)

Is the NTSC image also fixable?

**Comment by vossstef** [comment]
let me habe a Look into that

**Comment by vossstef** [comment]
@vanfanel 
i tried endless different hdmi settings in the NTSC mode and after all it looks that better leave "as is". sorry...

**Comment by vanfanel** [comment]
> @vanfanel i tried endless different hdmi settings in the NTSC mode and after all it looks that better leave "as is". sorry...

Don't worry. I Will use the core in PAL mode anyway, I am european and don't care much about NTSC software. 
Many thanks for trying!! I am sure you put a lot of time in trying values... And time does not come back.
