### ISSUE TITLE
DB9 joystick directions swaped

### ISSUE THREAD

**Issue by HaraldSimon** [vossstef/tang_nano_20k_c64#65]
I have a MisteryNano 20k board with DB9 joystick connector.
The DB9 joystick works fine with MiSTery core on several games.

With this C64 core flashed, the directions of the joystick are swaped:
Left is right and reverse.
Up is down and reverse.
Fire button works.

I searched the files and modified the file "tang_nano_20k_c64_top.cst" after the command "// generic IO pins to use for e.g. db9 joystick"
pin 28 <> pin 25
pin 26 <> pin 29

The file looks now this way:
..
// generic IO pins to use for e.g. db9 joystick
IO_LOC "io[0]" 27;
IO_PORT "io[0]" PULL_MODE=UP IO_TYPE=LVCMOS33;
IO_LOC "io[1]" 25;
IO_PORT "io[1]" PULL_MODE=UP IO_TYPE=LVCMOS33;
IO_LOC "io[2]" 28;
IO_PORT "io[2]" PULL_MODE=UP IO_TYPE=LVCMOS33;
IO_LOC "io[3]" 29;
IO_PORT "io[3]" PULL_MODE=UP IO_TYPE=LVCMOS33;
IO_LOC "io[4]" 26;
IO_PORT "io[4]" PULL_MODE=UP IO_TYPE=LVCMOS33;
..
After flashing the modified version, the DB9 joystick works as expected.

**Comment by vossstef** [comment]
bug confirmed with MiSTeryNano shield as Joystick Adapter.
Will be fixed in next release.

**Comment by vossstef** [comment]
@HaraldSimon pls. flash new misterynano fw and new fpga bitstream in branch https://github.com/vossstef/tang_nano_20k_c64/tree/63-porting-of-latest-redip-sid-pipelining-mode-for-tn20k-dual-sid-usecase
pls report any issues. thx !

**Comment by HaraldSimon** [comment]
I flashed the new core, DB9 joystick works now "out of the box" in correct manner.
Thanks.
