### ISSUE TITLE
Unloading .CRT doesn't work

### ISSUE THREAD

**Issue by vanfanel** [vossstef/tang_nano_20k_c64#71]
CRT files work perfectly well with the core, but once loaded, they can't be unloaded unless the system is physically power-cycled.
Unloading a CRT and then resetting doesn't work either.

**Comment by vossstef** [comment]
Hi @vanfanel, i wrote some hints how to operate in the readme.

To unload a CRT ROM you have first to set in  'STORAGE' , 'CRT ROM ' the setting 'No Disk' and then perform a 'ColdBoot' from the 'SYSTEM' Menue.

**Comment by vanfanel** [comment]
@vossstef Ah! I understand now. Sorry to open this as an issue, based on my own ignorance. 
And many thanks for the explanation!
