### ISSUE TITLE
Tape loading does not work with ExBasic Level II cartridge

### ISSUE THREAD

**Issue by 2fatninja** [vossstef/tang_nano_20k_c64#76]
Tape loading seems not to work when using the ExBasic Level II cartridge from Markt & Technik AG. 

When not using the cartridge image, tape files are found normally, however the loading screen remains blank if the cartridge is mounted.

**Comment by vossstef** [comment]
@2fatninja will check on that during the next weeks.

**Comment by vossstef** [comment]
@2fatninja 
i checked differnt exbasic versions and all don't work in conjunction with TAP load for whatever reason.
sorry but don't find time at the moment to figure out why exactly this happens.
Other basic extensions e.g. Simon Basic is working with TAP load

**Comment by vossstef** [comment]
@2fatninja 
just found a mrthod for correct working TAP load using the Exbasic II !

Simply use: 
**LOAD***

Exbasic TAP Speedloader will be disabled and some kind of compatibility mode invoked. Hope it will help to solve your topic.

**Comment by 2fatninja** [comment]
Many thanks for the workaround @vossstef !
I confirmed that it worked for me as well.
